### ISSUE TITLE
Disable D-pad hotkeys in non-game-pausing menus

### ISSUE THREAD

**Issue by ArrowToTheAss** [DaveDambonite/Loadout#2]
Hello.

Loadout is great and very helpfull with the exception of one very annoying bug.

I use a controller when i play skyrim and ofcourse use the Dpad in all menues. So when i 
use the Dpad with Loadout installed it changes the Loadout slot like it is supposed to. So here is the bug >  when i enter a menu (like Enchanting) and use the Dpad it changes the Loadout slot.

I'm hoping that you could fix this. A possible way to fix it is by adding an option to disable the controller support for Loadout with the help of SkyUi (I use SkyUi but dislike the way it looks so i also use SkyUi Away to get it to look normal again), or you could release a version of Loadout where the controller support has been removed.

Thank you in advance, i hope that my request isnt too much of an inconvinience.

**Comment by DaveDambonite** [comment]
I agree with you that this is a problem. 

I wont take the time to add options through SkyUI both because of the time required and because it adds a dependency.
